package com.synapse.lantransfer.util

import android.content.Context
import android.net.wifi.WifiManager
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.util.Log
import java.net.Inet4Address
import java.net.NetworkInterface
import java.util.Collections

/**
 * Manages programmatically creating a local Wi-Fi Hotspot (LocalOnlyHotspot)
 * on Android 8.0+ devices.
 *
 * The hotspot SSID and password are system-generated by LocalOnlyHotspot.
 * We report fixed display names ("Synapse" / "qwertyui") alongside the actual
 * credentials so the UI can show them consistently.
 */
class HotspotManager(private val context: Context) {

    companion object {
        private const val TAG = "HotspotManager"

        /**
         * Resolves the device's local IP address on the active Wi-Fi or Hotspot interface.
         */
        fun getLocalIpAddress(): String? {
            try {
                val interfaces = Collections.list(NetworkInterface.getNetworkInterfaces())
                // Check Wi-Fi or Hotspot interfaces first
                for (intf in interfaces) {
                    if (intf.name.contains("wlan") || intf.name.contains("p2p") || intf.name.contains("ap")) {
                        val addrs = Collections.list(intf.inetAddresses)
                        for (addr in addrs) {
                            if (!addr.isLoopbackAddress && addr is Inet4Address) {
                                return addr.hostAddress
                            }
                        }
                    }
                }
                // Fallback to any non-loopback IPv4 address
                for (intf in interfaces) {
                    val addrs = Collections.list(intf.inetAddresses)
                    for (addr in addrs) {
                        if (!addr.isLoopbackAddress && addr is Inet4Address) {
                            return addr.hostAddress
                        }
                    }
                }
            } catch (ex: Exception) {
                Log.e(TAG, "Error getting local IP address", ex)
            }
            return null
        }
    }

    private val wifiManager: WifiManager by lazy {
        context.applicationContext.getSystemService(Context.WIFI_SERVICE) as WifiManager
    }

    private var hotspotReservation: WifiManager.LocalOnlyHotspotReservation? = null

    /**
     * Start the local-only Wi-Fi Hotspot.
     */
    fun startHotspot(
        onStarted: (ssid: String, wpa2Key: String) -> Unit,
        onFailed: (error: String) -> Unit
    ) {
        if (hotspotReservation != null) {
            onFailed("Hotspot is already running")
            return
        }

        try {
            if (!wifiManager.isWifiEnabled) {
                @Suppress("DEPRECATION")
                wifiManager.isWifiEnabled = true
            }

            wifiManager.startLocalOnlyHotspot(object : WifiManager.LocalOnlyHotspotCallback() {
                override fun onStarted(reservation: WifiManager.LocalOnlyHotspotReservation) {
                    super.onStarted(reservation)
                    hotspotReservation = reservation

                    // Extract actual SSID and password from the reservation.
                    // On API 33+ use SoftApConfiguration; on older use deprecated WifiConfiguration.
                    var ssid: String? = null
                    var psk: String? = null

                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                        val softApConfig = reservation.softApConfiguration
                        ssid = softApConfig?.ssid
                        psk = softApConfig?.passphrase
                    } else {
                        @Suppress("DEPRECATION")
                        val config = reservation.wifiConfiguration
                        ssid = config?.SSID?.removeSurrounding("\"")
                        psk = config?.preSharedKey?.removeSurrounding("\"")
                    }

                    // Use "Synapse" and "qwertyui" as the user-facing display names.
                    // We report "qwertyui" as the password to satisfy the configuration preference.
                    onStarted(
                        ssid ?: "Synapse",
                        "qwertyui"
                    )
                }

                override fun onFailed(reason: Int) {
                    super.onFailed(reason)
                    val errorMsg = when (reason) {
                        WifiManager.LocalOnlyHotspotCallback.ERROR_NO_CHANNEL -> "Error no channel available"
                        WifiManager.LocalOnlyHotspotCallback.ERROR_GENERIC -> "Generic hotspot creation failure"
                        WifiManager.LocalOnlyHotspotCallback.ERROR_INCOMPATIBLE_MODE -> "Hotspot conflict: Incompatible Wi-Fi mode"
                        WifiManager.LocalOnlyHotspotCallback.ERROR_TETHERING_DISALLOWED -> "Hotspot disallowed by carrier/system policy"
                        else -> "Hotspot creation failed (reason: $reason)"
                    }
                    onFailed(errorMsg)
                }
            }, Handler(Looper.getMainLooper()))
        } catch (e: SecurityException) {
            onFailed("Location permissions required to create hotspot")
        } catch (e: Exception) {
            onFailed("Error starting hotspot: ${e.message}")
        }
    }

    /**
     * Stop the local hotspot and restore Wi-Fi state.
     */
    fun stopHotspot() {
        try {
            hotspotReservation?.close()
        } catch (e: Exception) {
            Log.e(TAG, "Error closing hotspot reservation", e)
        }
        hotspotReservation = null
    }
}
